### ISSUE TITLE
Permission denied on CSR creation

### ISSUE THREAD

**Issue by 9b** [ubergeek42/lambda-letsencrypt#20]
My domain has been authorized, but I am noticing a permission error when trying to create the CSR. This does not appear to be related to the S3 bucket policy. Is there some place I need to adjust?

> [INFO]    2016-06-28T21:55:03.355Z    f65419f0-3d7a-11e6-9eff-81dfcc33a282    Generate CSR and get cert for CloudFront Distribution MY_CLOUDFRONT_ID
> [WARNING] 2016-06-28T21:55:06.95Z f65419f0-3d7a-11e6-9eff-81dfcc33a282    [Errno 13] Permission denied: 'csr_test.der'

**Comment by 9b** [comment]
Commenting out the offending lines seem to fix the issue. 

https://github.com/ubergeek42/lambda-letsencrypt/blob/master/simple_acme.py#L348-L349

From what I can tell, this isn't used by any of the functions. Running the AWS CLI tool afterwards shows the certificates were successfully uploaded. Running into different errors now related to the validity of the certificate and associated chain.

**Comment by ubergeek42** [comment]
Ah, yes, those lines look to be unused(I made a quick commit and removed them). Let me know what you determine with regards to the certificate/chain.

Did you make sure to change the directory_url in the config to point at the production letsencrypt server? The staging one isn't trusted by any browsers and could be the cause of your issue.

https://github.com/ubergeek42/lambda-letsencrypt/blob/a356b5ea63650a7b06fd9defc68cdd4691926e4d/config.py.dist#L1 (also see #14 since there's an error; basically change the urls to not have /directory at the end of it)

**Comment by 9b** [comment]
I found that out, but also surfaced some other issues! We can close this!
